### ISSUE TITLE
Require answer to below question.

### ISSUE THREAD

**Issue by TheAlphamerc** [sendbird/SendBird-SDK-dotNET#11]
I have already been through official [send bird documentation](https://docs.sendbird.com/dotnet/group_channel) but didn't find answer to below question.
1. Is there any way to find out that any userId is registered or not in the group channel?
2. How to get users current status (Offline/Online)?
3. How to find user is typing or not .
4. How to identify UserId is not registered in groupChannel?

**Comment by Alchemist85K** [comment]
@TheAlphamerc 

1. Please check `groupChannel.Members`.
2. Please call the `GetConnectionState()` in `SendBirdClient`.
3. We provide `UserListQuery` to retrieve user list. And there is a filter.
```
UserListQuery query = SendBirdClient.CreateUserListQuery(userIds);
```
4. Please check `groupChannel.Members`.

Thank you for your interest in SendBird SDK.

**Comment by TheAlphamerc** [comment]
Whenever  SendBirdClient.GetPendingPushToken() is called to get token for push notification it return null. the code I used is below:-

` SendBirdClient.Connect(userId, (User user, SendBirdException e) => {
    if (e != null) {
        // Error.
        return;
    }

    if (SendBirdClient.GetPendingPushToken() == null) return;

    // For Android
    SendBirdClient.RegisterFCMPushTokenForCurrentUser(SendBirdClient.GetPendingPushToken(), (SendBirdClient.PushTokenRegistrationStatus status, SendBirdException e1) => {
        if (e1 != null) {
            // Error.
            return;
        }

        if (status == SendBirdClient.PushTokenRegistrationStatus.PENDING) {
            // Try registration after connection is established.
        }
    });

    // For iOS
    SendBirdClient.RegisterAPNSPushTokenForCurrentUser(SendBirdClient.GetPendingPushToken(), (SendBirdClient.PushTokenRegistrationStatus status, SendBirdException e1) => {
        if (e1 != null) {
            // Error.
            return;
        }

        if (status == SendBirdClient.PushTokenRegistrationStatus.PENDING) {
            // Try registration after connection is established.
        }
    });
});`

**Comment by Alchemist85K** [comment]
`GetPendingPushToken()`  is a function that checks the push-token registered using `RegisterAPNSPushTokenForCurrentUser()` or `RegisterFCMPushTokenForCurrentUser()`. Would you like to call them after using `RegisterAPNSPushTokenForCurrentUser()` or `RegisterFCMPushTokenForCurrentUser()`?

**Comment by TheAlphamerc** [comment]
If i call RegisterFCMPushTokenForCurrentUser() before GetPendingPushToken() it returns error exception `Invalid arguments.` with code `800110`

**Comment by Alchemist85K** [comment]
You have to pass two parameters. 
```
RegisterFCMPushTokenForCurrentUser(string fcmRegToken, RegisterPushTokenWithStatusHandler handler)
```
If you don't pass fcmRegToken as string, SDK returns error as `INVALID PARAMETER` with `800110` code.

**Comment by TheAlphamerc** [comment]
Thanks @Alchemist85K it works now I receive Success status from 
RegisterFCMPushTokenForCurrentUser(string fcmRegToken, RegisterPushTokenWithStatusHandler handler).

**Comment by TheAlphamerc** [comment]
@Alchemist85K When a registered user send message to another user then push notification sends notification automatically ? or this notification has to be sent programmatically from app ?

**Comment by Alchemist85K** [comment]
When another user sends a message from the GroupChannel with the user who registered push token, the user who registered push token receives a push notification if the user is offline.

**Comment by MirajM** [comment]
@Alchemist85K  I get the Success status from RegisterFCMPushTokenForCurrentUser(), But i dont get any notifications to the user who has registered push token. 

My OnMessageReceived Code Below, am I Missing Something here?
```
 public virtual void OnMessageReceived(object sender, Firebase.Messaging.MessageReceivedEventArgs e)
    {
        Debug.Log("Received a new message");
        var notification = e.Message.Notification;
        if (notification != null)
        {
            Debug.Log("title: " + notification.Title);
            Debug.Log("body: " + notification.Body);
            var android = notification.Android;
            if (android != null)
            {
                Debug.Log("android channel_id: " + android.ChannelId);
            }
        }
        if (e.Message.From.Length > 0)
            Debug.Log("from: " + e.Message.From);
        if (e.Message.Link != null)
        {
            Debug.Log("link: " + e.Message.Link.ToString());
        }
        if (e.Message.Data.Count > 0)
        {
            Debug.Log("data:");
            foreach (System.Collections.Generic.KeyValuePair<string, string> iter in
                     e.Message.Data)
            {
                Debug.Log("  " + iter.Key + ": " + iter.Value);
            }
        }
    }
```

**Comment by MirajM** [comment]
@TheAlphamerc is it working for you?

**Comment by TheAlphamerc** [comment]
@MirajM No, it didn't work for me also.
